apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coffee-and-tea
  namespace: argocd
spec:
  project: my-project
  source:
    repoURL: git@github.com:Midzaru2011/CoffeeAndTea.git
    targetRevision: master
    path: coffee-and-tea
    helm:
      valueFiles:
        - values.yaml
    parameters:
      - name: postgresPassword
        value: your password
  destination:
    server: https://kubernetes.default.svc 
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
