{{- if and .Values.istio.enabled .Values.istio.gateway.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "coffee-and-tea.gatewayName" . }}
  labels:
    {{- include "coffee-and-tea.labels" . | nindent 4 }}
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    {{- range .Values.istio.gateway.hosts }}
    - {{ . | quote }}
    {{- end }}
    {{- if .Values.istio.gateway.tls }}
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: {{ .Values.istio.gateway.tls.mode }}
      {{- if .Values.istio.gateway.tls.credentialName }}
      credentialName: {{ .Values.istio.gateway.tls.credentialName }}
      {{- end }}
    hosts:
    {{- range .Values.istio.gateway.hosts }}
    - {{ . | quote }}
    {{- end }}
    {{- end }}
{{- end }}