{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "coffee-and-tea.fullname" . }}-secret
  labels:
    {{- include "coffee-and-tea.labels" . | nindent 4 }}
type: Opaque
data:
  # Database password
  {{- if .Values.postgresql.enabled }}
  database.password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  {{- else }}
  database.password: {{ "admin" | b64enc | quote }}
  {{- end }}
  
  # Weather API key
  weather.api.key: {{ .Values.externalServices.openWeatherMap.apiKey | b64enc | quote }}
  
  # Additional secrets
  {{- with .Values.secret.data }}
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}