{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "coffee-and-tea.fullname" . }}
  labels:
    {{- include "coffee-and-tea.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "coffee-and-tea.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: {{ .Values.monitoring.serviceMonitor.path }}
    interval: {{ .Values.monitoring.serviceMonitor.interval }}
    scrapeTimeout: 30s
    honorLabels: true
{{- end }}