name: Build and Push Docker Image with Semantic Versioning

on:
  push:
    branches:
      - main # или другая ветка, на которой вы хотите запускать сборку
    tags:
      - 'v*' # Дополнительно можно добавить триггер на Git tags (например, v1.0.0)

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Выгрузка кода из репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Чтение версии из файла VERSION
      - name: Read version from file
        id: version
        run: echo "version=$(cat VERSION)" >> $GITHUB_ENV

      # Шаг 3: Логин в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Шаг 4: Сборка и отправка образа
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            midzaru2011/coffee-and-tea-app:v${{ env.version }} # Тег с версией
            midzaru2011/coffee-and-tea-app:latest # Опционально: тег latest
